// Code generated by "stringer -type fileOperation -output file_operation_string.go"; DO NOT EDIT.

package audio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opErr-0]
	_ = x[noop-1]
	_ = x[created-2]
	_ = x[skipped-3]
	_ = x[copied-4]
}

const _fileOperation_name = "opErrnoopcreatedskippedcopied"

var _fileOperation_index = [...]uint8{0, 5, 9, 16, 23, 29}

func (i fileOperation) String() string {
	if i < 0 || i >= fileOperation(len(_fileOperation_index)-1) {
		return "fileOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fileOperation_name[_fileOperation_index[i]:_fileOperation_index[i+1]]
}
