// Code generated by "stringer -type Format"; DO NOT EDIT.

package audio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[M4a-0]
	_ = x[Mp3-1]
	_ = x[Wav-2]
}

const _Format_name = "M4aMp3Wav"

var _Format_index = [...]uint8{0, 3, 6, 9}

func (i Format) String() string {
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
