// Code generated by "stringer -type TTSCmd"; DO NOT EDIT.

package audio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Say-0]
	_ = x[EspeakNG-1]
	_ = x[Custom-2]
}

const _TTSCmd_name = "SayEspeakNGCustom"

var _TTSCmd_index = [...]uint8{0, 3, 11, 17}

func (i TTSCmd) String() string {
	if i < 0 || i >= TTSCmd(len(_TTSCmd_index)-1) {
		return "TTSCmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TTSCmd_name[_TTSCmd_index[i]:_TTSCmd_index[i+1]]
}
